const stories = [
  {id:1,cat:'Общество',source:'Yle',time:'09:18',title:'В Финляндии начинается самый тёплый уикенд этого лета',text:'Метеорологи обещают солнечную погоду почти по всей стране. В южных регионах температура может подняться выше +25 градусов.',visual:'linear-gradient(135deg,#bfd9c5 0%,#e9cf80 45%,#7ba7a5 100%)',featured:true},
  {id:2,cat:'Политика',source:'Helsingin Sanomat',time:'08:45',title:'Правительство представило новые меры поддержки малого бизнеса',text:'Пакет решений направлен на сохранение рабочих мест и поддержку предпринимателей в регионах.'},
  {id:3,cat:'Культура',source:'Yle',time:'08:10',title:'В Савонлинне открылся оперный фестиваль',text:'В этом году на сцене старинной крепости покажут шесть постановок с артистами из разных стран.'},
  {id:4,cat:'Экономика',source:'Kauppalehti',time:'07:52',title:'Финские компании увеличили экспорт технологий',text:'Спрос на решения в области чистой энергетики остаётся ключевым драйвером роста.'},
  {id:5,cat:'Спорт',source:'Ilta-Sanomat',time:'07:30',title:'Сборная Финляндии готовится к решающему матчу',text:'Тренерский штаб объявил состав на игру, которая пройдёт уже в воскресенье.'},
  {id:6,cat:'Общество',source:'MTV Uutiset',time:'06:55',title:'Ночные поезда на севере страны стали популярнее',text:'Летом жители и туристы выбирают железную дорогу для путешествий в Лапландию.'}
];
const $ = s => document.querySelector(s);
let category='Все', query='', saved=JSON.parse(localStorage.getItem('suomi-saved')||'[]');
const featured = $('#featured'), articles = $('#articles'), empty=$('#empty'), count=$('#resultCount');
function card(s, isFeatured=false){const savedClass=saved.includes(s.id)?'saved':''; if(isFeatured)return `<article class="featured-card" data-id="${s.id}"><div class="cover" style="background:${s.visual}"><span class="tag">ГЛАВНОЕ</span></div><div class="article-copy"><span class="meta">${s.source} · сегодня, ${s.time} · ${s.cat}</span><h3>${s.title}</h3><p>${s.text}</p><a class="read" href="#">Читать перевод</a></div></article>`;return `<article class="article" data-id="${s.id}"><div class="article-top"><span class="source">${s.source} · ${s.time}</span><button class="save ${savedClass}" aria-label="Сохранить" data-save="${s.id}">${saved.includes(s.id)?'★':'☆'}</button></div><span class="meta">${s.cat}</span><h3>${s.title}</h3><p>${s.text}</p></article>`}
function render(){const visible=stories.filter(s=>(category==='Все'||s.cat===category)&&`${s.title} ${s.text} ${s.source}`.toLowerCase().includes(query)); const lead=visible.find(s=>s.featured);featured.innerHTML=lead?card(lead,true):'';articles.innerHTML=visible.filter(s=>s!==lead).map(s=>card(s)).join('');empty.hidden=visible.length>0;count.textContent=`${visible.length} ${visible.length===1?'материал':'материалов'}`;}
function openStory(id){const s=stories.find(x=>x.id===id);$('#dialogContent').innerHTML=`<span class="dialog-source">${s.source} · перевод с финского · ${s.time}</span><h2 class="dialog-title">${s.title}</h2><p class="dialog-text">${s.text} Это демонстрационный перевод новости. В полноценной версии сайта здесь размещается текст, автоматически переведённый с оригинального материала финского издания, с сохранением ссылки на источник.</p><a class="original" href="#" onclick="return false">Открыть оригинал на ${s.source} →</a>`;$('#articleDialog').showModal()}
$('#chips').addEventListener('click',e=>{if(!e.target.matches('.chip'))return;category=e.target.dataset.category;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===e.target));render()});
$('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});
document.addEventListener('click',e=>{const button=e.target.closest('[data-save]');if(button){e.stopPropagation();const id=+button.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('suomi-saved',JSON.stringify(saved));$('#savedCount').textContent=saved.length;render();return}const item=e.target.closest('[data-id]');if(item&&!e.target.closest('a'))openStory(+item.dataset.id)});
$('.close').onclick=()=>$('#articleDialog').close(); $('#savedCount').textContent=saved.length; $('#today').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('#tickerText').textContent=stories[0].title;render();
